version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # コンテナ内にnpmパッケージ用のボリュームを作成する
      - /home/node/node_modules
      # プロジェクトルートをホームディレクトリにマウントする
      - .:/home/node
    environment:
      - NODE_ENV=development
