[context.production]
  command = "npm run build"
  publish = "/public"
  [context.production.environment]
    GATSBY_TELEMETRY_DISABLED = "1"


[context.deploy-preview]
  command = "npm run build"
  publish = "/public"
  [context.deploy-preview.environment]
    GATSBY_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  command = "npm run build"
  publish = "/public"
  [context.branch-deploy.environment]
    GATSBY_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
