[context.production.environment]
  command = "npm run build"
  publish = "/public"

[context.deploy-preview.environment]
  command = "npm run build"
  publish = "/public"

[context.branch-deploy.environment]
  command = "npm run build"
  publish = "/public"
